env:
  global:
    - NODE_VERSION=6.9.4

language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - .nvm
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - nvm install node
  - npm install -g npm@4
  - npm install -g nativescript --ignore-scripts
  - tns usage-reporting disable
  - tns error-reporting disable
  - npm install

before_script:
  - android create avd --force -n test -t android-19 -b armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator

script:
  - npm run build-android
  - tns test android
  - npm run test-only-smoke-android
