version: 2

default_config: &default_config
  working_directory: ~/TNSTravisTest

ios_config: &ios_config
  macos:
    xcode: "9.2.0"

android_config: &android_config
  docker:
    - image: circleci/android:api-25-alpha
  environment:
    EMULATOR_API: "25"


jobs:
  node-setup:
    <<: *default_config
    docker:
        - image: circleci/node:8

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-v2-{{ checksum "package.json" }}

      - run:
          name: Setup NativeScript
          command: |
            export GRADLE_OPTS="-Dorg.gradle.daemon=false"
            npm install
            npx tns usage-reporting disable
            npx tns error-reporting disable

      - save_cache:
          key: npm-v2-{{ checksum "package.json" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ~/
          paths:
            - TNSTravisTest


  android-setup:
    <<: [*default_config, *android_config]

    steps:
      - attach_workspace:
          at: ~/

      - restore_cache:
          keys:
            - android-v1-{{ checksum "package.json" }}

      - run:
          name: Install Node
          command: |
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            sudo apt-get install -y nodejs

      # - run:
      #     name: Setup Android
      #     command: |
      #       brew update
      #       brew cask install android-sdk
      #       echo y | $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "platforms;android-"$EMULATOR_API "build-tools;27.0.2" "extras;android;m2repository" "extras;google;m2repository"

      # - run:
      #     name: Pre-start Android emulator
      #     command: |
      #       android list targets
      #       echo no | android create avd --force -n test -t "android-"$EMULATOR_API -b armeabi-v7a
      #       emulator -avd test -no-window &


      - run:
          name: "Build Android"
          command: |
            npm -v
            npx tns usage-reporting disable
            npx tns error-reporting disable
            npx tns prepare android
            npx tns build android

      - save_cache:
          key: android-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.gradle/caches/
            - ~/.gradle/wrapper/

      - persist_to_workspace:
          root: ~/
          paths:
            - TNSTravisTest


  ios-setup:
    <<: [*default_config, *ios_config]

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: Setup CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf

      - run:
          name: Pre-start iOS Simulator
          command: xcrun instruments -w "iPhone 8 (11.2) [" || true

      - run:
          name: "Build iOS"
          command: |
            npx tns usage-reporting disable
            npx tns error-reporting disable
            npx tns prepare ios
            npx tns build ios

      - persist_to_workspace:
          root: ~/
          paths:
            - TNSTravisTest


  unit-test-ios:
    <<: [*default_config, *ios_config]

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: "iOS Unit Tests"
          command: |
            npx tns usage-reporting disable
            npx tns error-reporting disable
            npx tns test ios --justlaunch


  unit-test-android:
    <<: [*default_config, *android_config]

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: "Android Unit Tests"
          command: |
            npx tns usage-reporting disable
            npx tns error-reporting disable
            npx tns test android --justlaunch


  deploy:
    <<: *default_config

    docker:
        - image: circleci/node:8

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: "Deploy"
          command: echo "DEPLOY !!!"

workflows:
  version: 2
  main_workflow:
    jobs:
      - node-setup

      - android-setup:
          requires:
            - node-setup
      - ios-setup:
          requires:
            - node-setup

      - unit-test-android:
          requires:
            - android-setup
      - unit-test-ios:
          requires:
            - ios-setup

      - deploy:
          requires:
            - unit-test-android
            - unit-test-ios
