version: 2

default_config: &default_config
  working_directory: ~/TNSTravisTest
  macos:
    xcode: "9.2.0"
  environment:
    ANDROID_HOME: "/usr/local/share/android-sdk"

jobs:
  build:
    <<: *default_config

    steps:
      - checkout

      - restore_cache:
          keys:
            - npm-v1-{{ checksum "package.json" }}

      - run:
          name: Setup CocoaPods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf

      - run:
          name: Setup Android
          command: |
            brew update
            brew cask install android-sdk
            echo y | $ANDROID_HOME/tools/bin/sdkmanager "platform-tools" "platforms;android-25" "build-tools;27.0.2" "extras;android;m2repository" "extras;google;m2repository"

      - run:
          name: Setup NativeScript
          command: |
            npm i nativescript@3 --ignore-scripts
            npm install appium@1.7.2
            npm install
            npx tns usage-reporting disable
            npx tns error-reporting disable

      - save_cache:
          key: npm-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Pre-start simulator
          command: xcrun instruments -w "iPhone 8 (11.2) [" || true

      - run:
          name: "Build iOS"
          command: |
            npx tns prepare ios
            npx tns build ios

      - run:
          name: "Build Android"
          command: |
            npx tns prepare android
            npx tns build android

      - persist_to_workspace:
          root: ~/
          paths:
            - TNSTravisTest

  unit-test-ios:
    <<: *default_config

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: "iOS Unit Tests"
          command: |
            npx tns usage-reporting disable
            npx tns error-reporting disable
            npx tns test ios --justlaunch

  unit-test-android:
    <<: *default_config

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: "iOS Unit Tests"
          command: |
            npx tns usage-reporting disable
            npx tns error-reporting disable
            npx tns test android --justlaunch

  deploy:
    <<: *default_config

    steps:
      - attach_workspace:
          at: ~/

      - run:
          name: "Deploy"
          command: echo "DEPLOY !!!"

workflows:
  version: 2
  main_workflow:
    jobs:
      - build
      - unit-test-ios:
          requires:
            - build
      - unit-test-android:
          requires:
            - build
      - deploy:
          requires:
            - unit-test-ios
            - unit-test-android
