machine:
  xcode:
    version: 9.0.1
dependencies:
  cache_directories:
    - ~/.npm
    - ~/Library/Caches/Homebrew
    - ~/Library/Caches/CocoaPods
  pre:
    # Fetch cocoapods specs from S3 instead of github
    - curl -sS https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash
    - npm i -g nativescript --ignore-scripts
  override:
    - npm set progress=false && npm install
  post:
    # Pre-start emulator you'll use for the specs
    - xcrun instruments -w "iPhone 7 (11.0.1) [":
        background: true
compile:
  override:
    # Build Test App
    - tns prepare ios || echo "ios prepare"
    # - tns build ios
test:
  override:
    # E2E
    - tns test ios
  post:
    # Export results as artifacts downloadable
    # - mv e2e/reports/**/* $CIRCLE_ARTIFACTS/
general:
  branches:
    only: # list of branches to listen to
      - master
      - develop
